name: Apple Provisioning Profile Action
description: Install a provision profile on macOS runners for Xcode development
author: Nicholas Wong
branding:
  icon: anchor
  color: orange
inputs:
  profile-base64:
    description: The Apple provisioning profile which is base64 encoded
    required: false
  profile-file:
    description: Path to the Apple provisioning profile
    required: false
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo STRING=$(dd bs=512 if=/dev/urandom count=1 2>/dev/null | LC_ALL=C tr -dc 'a-zA-Z0-9' | fold -w 20 | head -n 1) >> "$GITHUB_OUTPUT"
      id: random
    - shell: bash
      if: ${{ inputs.profile-file != null }}
      run: cp ${{ inputs.profile-file }} $RUNNER_TEMP/${{ steps.random.outputs.STRING }}.provisionprofile
    - shell: bash
      if: ${{ inputs.profile-base64 != null }}
      run: echo -n ${{ inputs.profile-base64 }} | base64 --decode -o $RUNNER_TEMP/${{ steps.random.outputs.STRING }}.provisionprofile
    - shell: bash
      run: |
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp $RUNNER_TEMP/${{ steps.random.outputs.STRING }}.provisionprofile ~/Library/MobileDevice/Provisioning\ Profiles
